# Generated by Django 4.0.4 on 2022-05-06 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dpi', models.CharField(blank=True, max_length=16, null=True)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
