# Generated by Django 4.0.4 on 2022-05-10 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('state', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estacion.level')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estacion.position')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estacion.sector')),
            ],
            options={
                'unique_together': {('level', 'sector', 'number', 'position')},
            },
        ),
    ]
